name: Docker Image CI

on:
  release:
    types: [published]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: build and push
      uses: docker/build-push-action@v2
      with:
        registry: ghcr.io
        username: "CAMELS-DE"
        password: ${{ secrets.PAT }}
        repository: camels-de/dataset-builder
        tags: latest,${{ github.ref_name }}